### ISSUE TITLE
Cannot use in private repo

### ISSUE THREAD

**Issue by michaelsawyers** [zeroheight/action-design-system-adoption#3]
Using this action in a private repo and its failing with error: `Unable to resolve action. Repository not found: zh-ski/action-design-system-adoption`

My assumption is that this is happening due to being run from private repo after digging into the error message, after reading this https://github.com/actions/checkout/issues/254. 

```yaml
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows manual triggering

name: Adoption Analytics
jobs:
  analyze-and-track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Track package version
        uses: zh-ski/action-design-system-adoption@v2
        with:
          command: 'analyze'
          arguments: '--ignore "**/*.spec.*'
        env:
          ZEROHEIGHT_CLIENT_ID: '${{ secrets.ZEROHEIGHT_CLIENT_ID }}'
          ZEROHEIGHT_ACCESS_TOKEN: '${{ secrets.ZEROHEIGHT_ACCESS_TOKEN }}'
```
